### ISSUE TITLE
Ini kondisinya bener gini?

### ISSUE THREAD

**Issue by snaztoz** [aanarfian/TugasKripto#5]
https://github.com/aanarfian/TugasKripto/blob/88b4c4608fc8fac1ab617d10a00b992ad80d6686/ui.py#L61-L64

**Comment by aanarfian** [comment]
itu error kayaknya kalo dijalanin fid makanya biar ngga dijalananin pakai itu..

**Comment by aanarfian** [comment]
ngga tau cara lain wkwk :v

**Comment by aanarfian** [comment]
soalnya tipe nya none

**Comment by snaztoz** [comment]
Bukan gini?

```python
if key_enk_a != -1 and key_enk_b != -1:
```

**Comment by aanarfian** [comment]
oh iya wkwk

**Comment by snaztoz** [comment]
kamu apa aku aja yang benerin?

**Comment by aanarfian** [comment]
aku aja wkwk
ty gan

**Comment by snaztoz** [comment]
okey okey

**Comment by snaztoz** [comment]
aku close ya ini
